---
#add repository
- name : update os
  command : yum update
- name : ensure APT official nginx key
  apt_key : url= url=http://nginx.org/keys/nginx_signing.key
  environment: "{{ nginx_env }}"
  when: ansible_os_family == 'Debian'
- name :  Ensure APT official nginx repository
  apt_repository: repo="deb http://nginx.org/packages/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} nginx"
  environment: "{{ nginx_env }}"
  when: ansible_os_family == 'Debian' and not nginx_official_repo_mainline

- name: Ensure APT official nginx repository (mainline)
  apt_repository: repo="deb http://nginx.org/packages/mainline/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} nginx"
  environment: "{{ nginx_env }}"
  when: ansible_os_family == 'Debian' and nginx_official_repo_mainline

- name: Ensure RPM official nginx key
  rpm_key: key=http://nginx.org/keys/nginx_signing.key
  environment: "{{ nginx_env }}"
  when: ansible_os_family == 'RedHat'
- name : ensure yum official nginx repo
  template :
    src : nginx.repo.j2
    dest : /etc/yum.repo.d/nginx.repo
    when : ansible_os_family == "RedHat"

###another way
#- apt_repository:
 # repo : deb ttp://rpms.famillecollet.com/enterprise/remi-release-7.rpm
  #state : present
  #when ansible_os_family == "CentOS" and ansible_distribution_version == "7"
#- apt_repository :
 # repo : 'ppa:nginx/stable'
  #when ansible_os_family == "Ubuntu"
#- apt_repository :
 # repo : 'ppa:nginx/stable'
  #codename : 'trusty'
  #when ansible_os_family == "Debian"

