---
- name : install nginx
  yum :
    name : nginx
    state : latest
    enablerepo : nginx, remi
    when ansible_os_family == "CentOS" and ansible_distributions_version == " 7"
- name : stop httpd
  service :
    name : httpd
    state : stop
    enable : no
- name : start nginx
  service :
    name : nginx
    state : started
    enable : yes
    when: ansible_distribution == "CentOS" and ansible_distribution_version == '7'
- name : validate nginx configure
  command : nginx -t -c /etc/nginx/nginx.conf
  change_when : false
  when: ansible_distribution == "CentOS" and ansible_distribution_version == '7'
- name : reload nginx
  service :
    name : nginx
    state : reloaded
    when: ansible_distribution == "CentOS" and ansible_distribution_version == '7'

- name : create default page
  template :
    src : index.html
    dest : {{ nginx_conf_dir  }}/index.html
  command : echo " xin chao " >> index.html

